name: environment-teardown
description: Teardown preview after merge

inputs:
  github-token:
    description: 'The GitHub token for the account that hosts your app'
    required: true
  amplify-app-id:
    description: 'The ID for your app which you can get from the end of its ARN'
    required: true
  aws-region:
    description: 'The AWS region from which to tear down your app'
    required: true
  aws-role-arn:
    description: 'The AWS IAM role ARN to assume for OIDC authentication'
    required: true
  environment-name:
    description: 'GitHub environment name to delete'
    required: true
  branch-name:
    description: 'Amplify "branch" name'
    required: true

runs:
  using: composite
  steps:
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
    with:
      role-to-assume: ${{ inputs.aws-role-arn }}
      role-session-name: github-actions-amplify-teardown-${{ github.run_id }}
      aws-region: ${{ inputs.aws-region }}

  - name: Delete associated GitHub environment
    uses: strumwolf/delete-deployment-environment@v2.2.3
    with:
      token: ${{ inputs.github-token }}
      environment: ${{ inputs.environment-name }}

  - name: Delete Amplify branch
    shell: bash
    run: |
      aws amplify delete-branch \
        --app-id ${{ inputs.amplify-app-id }} \
        --branch-name ${{ inputs.branch-name }}
    env:
      AWS_REGION: ${{ inputs.aws-region }}