const percyPagesByApp = {
    'nextjs-app-v14': [
        { url: '/', name: 'PIE Aperture' },
        { url: '/components/assistive-text', name: 'Assistive Text' },
        { url: '/components/avatar', name: 'Avatar' },
        { url: '/components/button', name: 'Button' },
        { url: '/components/breadcrumb', name: 'Breadcrumb' },
        { url: '/components/card', name: 'Card' },
        { url: '/components/checkbox', name: 'Checkbox' },
        { url: '/components/checkbox-group', name: 'Checkbox Group' },
        { url: '/components/chip', name: 'Chip' },
        { url: '/components/cookie-banner', name: 'Cookie Banner' },
        { url: '/components/custom-tag', name: 'Custom Tag' },
        { url: '/components/divider', name: 'Divider' },
        { url: '/integrations/css-only-radio', name: 'CSS Only Radio' },
        { url: '/integrations/uncontrolled-form', name: 'Uncontrolled Form' },
        { url: '/integrations/controlled-form', name: 'Controlled Form' },
        { url: '/integrations/typography-classes', name: 'Typography Demo (CSS Classes)' },
        { url: '/integrations/typography-mixins', name: 'Typography Demo (Mixins)' },
        { url: '/components/form-label', name: 'Form Label' },
        { url: '/components/icon', name: 'Icon' },
        { url: '/components/icon-button', name: 'Icon Button' },
        { url: '/components/link', name: 'Link' },
        { url: '/components/lottie-player', name: 'Lottie Player', pauseBeforeScreenshot: true },
        { url: '/components/modal', name: 'Modal' },
        { url: '/components/notification', name: 'Notification' },
        { url: '/components/radio', name: 'Radio' },
        { url: '/components/radio-group', name: 'Radio Group' },
        { url: '/components/spinner', name: 'Spinner' },
        { url: '/components/switch', name: 'Switch' },
        { url: '/components/select', name: 'Select' },
        { url: '/components/tag', name: 'Tag' },
        { url: '/components/text-input', name: 'Text Input' },
        { url: '/components/textarea', name: 'Textarea' },
        { url: '/components/toast', name: 'Toast' },
        { url: '/components/thumbnail', name: 'Thumbnail' },
    ],
    'nextjs-app-v15': [
        { url: '/', name: 'PIE Aperture' },
        { url: '/components/assistive-text', name: 'Assistive Text' },
        { url: '/components/avatar', name: 'Avatar' },
        { url: '/components/breadcrumb', name: 'Breadcrumb' },
        { url: '/components/button', name: 'Button' },
        { url: '/components/card', name: 'Card' },
        { url: '/components/checkbox', name: 'Checkbox' },
        { url: '/components/checkbox-group', name: 'Checkbox Group' },
        { url: '/components/chip', name: 'Chip', pauseBeforeScreenshot: true },
        { url: '/components/cookie-banner', name: 'Cookie Banner' },
        { url: '/components/divider', name: 'Divider' },
        { url: '/integrations/css-only-radio', name: 'CSS Only Radio' },
        { url: '/integrations/uncontrolled-form', name: 'Uncontrolled Form' },
        { url: '/integrations/controlled-form', name: 'Controlled Form' },
        { url: '/integrations/typography-classes', name: 'Typography Demo (CSS Classes)' },
        { url: '/integrations/typography-mixins', name: 'Typography Demo (Mixins)' },
        { url: '/components/form-label', name: 'Form Label' },
        { url: '/components/icon', name: 'Icon' },
        { url: '/components/icon-button', name: 'Icon Button' },
        { url: '/components/link', name: 'Link' },
        { url: '/components/lottie-player', name: 'Lottie Player', pauseBeforeScreenshot: true },
        { url: '/components/modal', name: 'Modal' },
        { url: '/components/notification', name: 'Notification' },
        { url: '/components/radio', name: 'Radio' },
        { url: '/components/radio-group', name: 'Radio Group' },
        { url: '/components/select', name: 'Select' },
        { url: '/components/spinner', name: 'Spinner', pauseBeforeScreenshot: true },
        { url: '/components/switch', name: 'Switch' },
        { url: '/components/tag', name: 'Tag' },
        { url: '/components/text-input', name: 'Text Input' },
        { url: '/components/textarea', name: 'Textarea' },
        { url: '/components/toast', name: 'Toast' },
        { url: '/components/thumbnail', name: 'Thumbnail' },
    ],
    'nuxt-app': [
        { url: '/', name: 'PIE Aperture' },
        { url: '/components/assistive-text', name: 'Assistive Text' },
        { url: '/components/avatar', name: 'Avatar' },
        { url: '/components/button', name: 'Button' },
        { url: '/components/breadcrumb', name: 'Breadcrumb' },
        { url: '/components/card', name: 'Card' },
        { url: '/components/checkbox', name: 'Checkbox' },
        { url: '/components/checkbox-group', name: 'Checkbox Group' },
        { url: '/components/chip', name: 'Chip' },
        { url: '/components/cookie-banner', name: 'Cookie Banner' },
        { url: '/components/custom-tag', name: 'Custom Tag' },
        { url: '/components/divider', name: 'Divider' },
        { url: '/integrations/css-only-radio', name: 'CSS Only Radio' },
        { url: '/integrations/form', name: 'Form' },
        { url: '/integrations/typography-classes', name: 'Typography Demo (CSS Classes)' },
        { url: '/integrations/typography-mixins', name: 'Typography Demo (Mixins)' },
        { url: '/components/form-label', name: 'Form Label' },
        { url: '/components/icon', name: 'Icon' },
        { url: '/components/icon-button', name: 'Icon Button' },
        { url: '/components/link', name: 'Link' },
        { url: '/components/lottie-player', name: 'Lottie Player', pauseBeforeScreenshot: true },
        { url: '/components/modal', name: 'Modal' },
        { url: '/components/notification', name: 'Notification' },
        { url: '/components/radio', name: 'Radio' },
        { url: '/components/radio-group', name: 'Radio Group' },
        { url: '/components/spinner', name: 'Spinner' },
        { url: '/components/switch', name: 'Switch' },
        { url: '/components/select', name: 'Select' },
        { url: '/components/tag', name: 'Tag' },
        { url: '/components/text-input', name: 'Text Input' },
        { url: '/components/textarea', name: 'Textarea' },
        { url: '/components/toast', name: 'Toast' },
        { url: '/components/thumbnail', name: 'Thumbnail' },
    ],
    'vanilla-app': [
        { url: '/index.html', name: 'PIE Aperture' },
        { url: '/components/assistive-text.html', name: 'Assistive Text' },
        { url: '/components/avatar.html', name: 'Avatar' },
        { url: '/components/button.html', name: 'Button' },
        { url: '/components/breadcrumb.html', name: 'Breadcrumb' },
        { url: '/components/card.html', name: 'Card' },
        { url: '/components/checkbox.html', name: 'Checkbox' },
        { url: '/components/checkbox-group.html', name: 'Checkbox Group' },
        { url: '/components/chip.html', name: 'Chip' },
        { url: '/components/cookie-banner.html', name: 'Cookie Banner' },
        { url: '/components/custom-tag.html', name: 'Custom Tag' },
        { url: '/components/divider.html', name: 'Divider' },
        { url: '/integrations/css-only-radio.html', name: 'CSS Only Radio' },
        { url: '/integrations/form.html', name: 'Form' },
        { url: '/integrations/typography-classes.html', name: 'Typography Demo (CSS Classes)' },
        { url: '/integrations/typography-mixins.html', name: 'Typography Demo (Mixins)' },
        { url: '/components/form-label.html', name: 'Form Label' },
        { url: '/components/icon.html', name: 'Icon' },
        { url: '/components/icon-button.html', name: 'Icon Button' },
        { url: '/components/link.html', name: 'Link' },
        { url: '/components/lottie-player.html', name: 'Lottie Player', pauseBeforeScreenshot: true },
        { url: '/components/modal.html', name: 'Modal' },
        { url: '/components/notification.html', name: 'Notification' },
        { url: '/components/radio.html', name: 'Radio' },
        { url: '/components/radio-group.html', name: 'Radio Group' },
        { url: '/components/spinner.html', name: 'Spinner' },
        { url: '/components/switch.html', name: 'Switch' },
        { url: '/components/select.html', name: 'Select' },
        { url: '/components/tag.html', name: 'Tag' },
        { url: '/components/text-input.html', name: 'Text Input' },
        { url: '/components/textarea.html', name: 'Textarea' },
        { url: '/components/toast.html', name: 'Toast' },
        { url: '/components/thumbnail.html', name: 'Thumbnail' },
    ],
};

export function getPercyPages(appName) {
    const pages = percyPagesByApp[appName];

    if (!pages) {
        throw new Error(`No Percy page configuration found for app '${appName}'.`);
    }

    return pages;
}