import type { Metadata } from "next";
import Head from "next/head";
import "@justeattakeaway/pie-css";
import "@/styles/main.scss";
import "@/styles/icons.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>PIE Aperture</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Component {...pageProps} />
    </html>
  );
}
