import Head from 'next/head'
import { Inter } from 'next/font/google'
import { PieButton } from '@justeattakeaway/pie-button/dist/react';

const inter = Inter({ subsets: ['latin'] })
// @ts-ignore
export default function Layout({ children }) {
  return (
    <>
        <Head>
            <title>PIE Aperture</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${inter.className} main`}>
            {children}
        </main>
    </>
  )
}