name: Build - NextJS 14 App

on: [push]

jobs:
  build-deploy-next-app-ubuntu:
    name: Ubuntu
    uses: ./.github/workflows/build.yml
    with:
        deploy: false
        os: 'ubuntu-latest'
        package-name: 'nextjs-app-v14'
