name: Build - NextJS App

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, "ready_for_review"]
    paths:
      - '.github/workflows/**'
      - 'nextjs-app-v13/**'
      - 'nextjs-app-v14/**'
      - 'webdriver-helpers/**'
      - 'wdio.conf.js'

  push:
    branches:
      - main

concurrency:
  group: CI-NextJS-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:

  # Commenting these out for now as there's currently an issue with Next.
  # build-next-app-windows-node18:
  #   name: Windows - Node 18
  #   uses: ./.github/workflows/build.yml
  #   with:
  #       deploy: false
  #       node-version: 18
  #       os: 'windows-latest'
  #       package-name: 'nextjs-app-v13'
  #   secrets: inherit

  # build-next-app-windows-node20:
  #   name: Windows - Node 20
  #   uses: ./.github/workflows/build.yml
  #   with:
  #       deploy: false
  #       node-version: 20
  #       os: 'windows-latest'
  #       package-name: 'nextjs-app-v13'
  #   secrets: inherit

  build-next-app:
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest]
        include:
          - node-version: 18
            os: ubuntu-latest
            package-name: 'nextjs-app-v13'

          - node-version: 20
            os: ubuntu-latest
            package-name: 'nextjs-app-v13'
            deploy: true
            amplify-app-id: 'd1106vmj1ozg8d'
            package-dist-directory: './nextjs-app-v13/out'
            bucket-name-preview: 'pie-aperture-preview'
            bucket-name-main: 'pie-aperture'

          - node-version: 18
            os: ubuntu-latest
            package-name: 'nextjs-app-v14'

          - node-version: 20
            os: ubuntu-latest
            package-name: 'nextjs-app-v14'
            deploy: true
            amplify-app-id: 'd1xxjuy6vbm7pk'
            package-dist-directory: './nextjs-app-v14/out'
            bucket-name-preview: 'pie-aperture-preview'
            bucket-name-main: 'pie-aperture'

    name: Build ${{ matrix.package-name }} - Node ${{ matrix.node-version }} on ${{ matrix.os }}
    uses: ./.github/workflows/build.yml
    with:
      deploy: ${{ matrix.deploy || false }}
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
      package-name: ${{ matrix.package-name }}
      amplify-app-id: ${{ matrix.amplify-app-id || '' }}
      package-dist-directory: ${{ matrix.package-dist-directory || '' }}
      bucket-name-preview: ${{ matrix.bucket-name-preview || '' }}
      bucket-name-main: ${{ matrix.bucket-name-main || '' }}
    secrets: inherit

  browser-tests:
    needs: [build-next-app]
    name: Run System / Visual Tests
    runs-on: ubuntu-latest
    steps:
        # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v3

        # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Dependencies
        shell: bash
        run: yarn

        # Setup Playwright
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Run System Tests
        shell: bash
        run: yarn test:system --filter=${{ needs.build-next-app.outputs.package-name }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nextjs-playwright-report
          path: playwright-reports/nextjs-playwright-report/
          retention-days: 7

      - name: Run Percy Tests
        shell: bash
        run: yarn test:visual --filter=${{ needs.build-next-app.outputs.package-name }}

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NEXT_AMPLIFY_ID: d1106vmj1ozg8d
      NEXT_14_AMPLIFY_ID: d1xxjuy6vbm7pk
      PERCY_TOKEN_PIE_APERTURE_NEXT_13: ${{ secrets.PERCY_TOKEN_PIE_APERTURE_NEXT_13 }}
      PERCY_TOKEN_PIE_APERTURE_NEXT_14: ${{ secrets.PERCY_TOKEN_PIE_APERTURE_NEXT_14 }}
      PR_NUMBER: ${{ github.event.number }}