name: Build - NextJS 15 App

on:
  pull_request:
    types: [opened, synchronize, reopened, "ready_for_review"]
    paths:
      - '.github/workflows/**'
      - 'nextjs-app-v15/**'
      - 'playwright.percy.config.ts'
      - 'test/**'
      - 'playwright-helpers/**'
      - '.percy.yml'
      - 'package.json'
      - 'yarn.lock'

  push:
    branches:
      - main

concurrency:
  group: CI-NextJS-15-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:

  # Commenting this out for now as there's currently an issue with Next.

  # build-next-app-windows-node20:
  #   name: Windows - Node 20
  #   uses: ./.github/workflows/build.yml
  #   with:
  #       deploy: false
  #       node-version: 20
  #       os: 'windows-latest'
  #       package-name: 'nextjs-app-v15'
  #   secrets: inherit


  build-deploy-next-app-ubuntu-node20:
      name: Ubuntu - Node 20
      uses: ./.github/workflows/build.yml
      with:
          deploy: true
          node-version: 20
          os: 'ubuntu-latest'
          amplify-app-id: 'dg9syjb0jj07x'
          package-name: 'nextjs-app-v15'
          package-dist-directory: './nextjs-app-v15/out'
          bucket-name-preview: 'pie-aperture-preview'
          bucket-name-main: 'pie-aperture'
          aws-role-arn: ${{ vars.AWS_ROLE_ARN }}
      secrets: inherit

  system-tests:
    needs: 'build-deploy-next-app-ubuntu-node20'
    name: Run System Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Dependencies
        shell: bash
        run: yarn

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Run SSR Tests
        shell: bash
        run: yarn test:ssr --filter=nextjs-app-v15

      - name: Run System Tests
        shell: bash
        run: yarn test:system --filter=nextjs-app-v15

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        if: always()
        with:
          name: nextjs-playwright-report
          path: playwright-reports/nextjs-app-v15-playwright-report/
          retention-days: 7
    env:
      NEXT_15_AMPLIFY_ID: dg9syjb0jj07x
      PR_NUMBER: ${{ github.event.number }}

  percy-tests:
    needs: 'build-deploy-next-app-ubuntu-node20'
    if: (github.event_name == 'pull_request' && github.event.pull_request.draft == false) || github.ref == 'refs/heads/main'
    name: Run Percy Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Dependencies
        shell: bash
        run: yarn

      - name: Run Percy Tests
        shell: bash
        run: yarn test:visual --filter=nextjs-app-v15
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PERCY_TOKEN_PIE_APERTURE_NEXT_15: ${{ secrets.PERCY_TOKEN_PIE_APERTURE_NEXT_15 }}
      NEXT_15_AMPLIFY_ID: dg9syjb0jj07x
      PR_NUMBER: ${{ github.event.number }}

  chromatic-tests:
    needs: 'build-deploy-next-app-ubuntu-node20'
    if: (github.event_name == 'pull_request' && github.event.pull_request.draft == false) || github.ref == 'refs/heads/main'
    name: Run Chromatic Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Dependencies
        shell: bash
        run: yarn

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Run Chromatic Tests
        shell: bash
        run: yarn test:visual:chromatic --filter=nextjs-app-v15

      - name: Upload Chromatic Results
        shell: bash
        run: npx chromatic --playwright --exit-zero-on-changes -t=${CHROMATIC_PROJECT_TOKEN}
    env:
      CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
      CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
      CHROMATIC_SLUG: ${{ github.repository }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN_NEXT15 }}
      NEXT_15_AMPLIFY_ID: dg9syjb0jj07x
      PR_NUMBER: ${{ github.event.number }}
